image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: ALFA IDE Setup
    before: gp env ALFA_HOME=$THEIA_WORKSPACE_ROOT/.alfa && curl -L --http1.1 http://alfa-lang.io/downloads/alfa-0.9.0-RC1.vsix --output /tmp/alfa-0.9.0-RC1.vsix > /dev/null && cd /tmp && jar xf alfa-0.9.0-RC1.vsix && mkdir -p /home/gitpod/.gitpod-code/extensions/ && mv extension /home/gitpod/.gitpod-code/extensions/schemarise.alfa-0.9.0-RC1
    command: exit

  - name: ALFA CLI Setup
    before: mkdir -p $THEIA_WORKSPACE_ROOT/.alfa && curl -L --http1.1 http://alfa-lang.io/downloads/AlfaCLI-0.9.0-RC1.zip --output $THEIA_WORKSPACE_ROOT/.alfa/AlfaCLI-0.9.0-RC1.zip > /dev/null && cd $THEIA_WORKSPACE_ROOT/.alfa && jar xf AlfaCLI-0.9.0-RC1.zip
    command: exit
    
  - name: ALFA Python Setup
    before: curl -L --http1.1 http://alfa-lang.io/downloads/alfa-pylib-0.9.0.tar.gz --output /tmp/alfa-pylib-0.9.0.tar.gz > /dev/null && pip install /tmp/alfa-pylib-0.9.0.tar.gz
    command: exit

  - name: Dot Setup
    before: sudo apt-get install graphviz -y 
    command: exit
    
  - command: exit  
    
vscode:
  extensions:
    - schemarise.alfa

ports:
  - port: 8000
    visibility: private
    onOpen: ignore
