image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: ALFA IDE Setup
    before: if gp env | grep -q ALFA_HOME; then gp env -u ALFA_HOME; fi && gp env ALFA_HOME=$HOME/.alfa && curl -L --http1.1 http://alfa-lang.io/downloads/alfa-3.0.1.vsix --output /tmp/alfa-3.0.1.vsix > /dev/null && cd /tmp && unzip -d p1 alfa-3.0.1.vsix && mkdir -p /workspace/.vscode-remote/extensions/ && mv p1/extension /workspace/.vscode-remote/extensions/schemarise.alfa-3.0.1
    command: exit

  - name: ALFA Assistant Setup
    before: curl -L --http1.1 http://alfa-lang.io/downloads/alfa-assistant-3.0.1.vsix --output /tmp/alfa-assistant-3.0.1.vsix > /dev/null &&             cd /tmp && unzip -d p2 alfa-assistant-3.0.1.vsix &&   mkdir -p /workspace/.vscode-remote/extensions/ && mv p2/extension /workspace/.vscode-remote/extensions/schemarise.alfa-assistant-3.0.1
    command: exit

  - name: ALFA CLI Setup
    before: mkdir -p $HOME/.alfa && curl -L --http1.1 http://alfa-lang.io/downloads/AlfaPackage-3.0.1.zip --output $HOME/.alfa/AlfaPackage-3.0.1.zip > /dev/null && cd $HOME/.alfa && unzip AlfaPackage-3.0.1.zip && rm -rf samples
    command: exit

  - name: ALFA Trial License Setup
    before: mkdir -p $HOME/.alfa && curl -L --http1.1 http://raw.githubusercontent.com/alfa-demo/alfa-sample-project/main/.alfa/alfa-license.txt --output $HOME/.alfa/alfa-license.txt > /dev/null
    command: exit

  - name: ALFA Python Setup
    before: curl -L --http1.1 http://alfa-lang.io/downloads/alfa-pylib-3.0.1.tar.gz --output /tmp/alfa-pylib-3.0.1.tar.gz > /dev/null && pip install /tmp/alfa-pylib-3.0.1.tar.gz
    command: exit

  - name: Dot Setup
    before: sudo apt-get install graphviz -y 
    command: exit
    
  - command: exit  
    
vscode:
  extensions:
    - schemarise.alfa

ports:
  - port: 8000
    visibility: private
    onOpen: ignore
